-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Czas generowania: 30 Maj 2018, 00:54
-- Wersja serwera: 10.1.30-MariaDB
-- Wersja PHP: 7.2.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Baza danych: `integracje_zaliczenie`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `channel`
--

CREATE TABLE `channel` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8_unicode_ci,
  `thumbnail` longtext COLLATE utf8_unicode_ci,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Zrzut danych tabeli `channel`
--

INSERT INTO `channel` (`id`, `name`, `description`, `thumbnail`, `createdAt`, `updatedAt`) VALUES
(2, 'Impact IT Sp z o.o.', 'Witamy na kanale YouTube firmy Impact IT. Założyliśmy ten kanał z myślą o wszystkich tych, którzy szukają kursów z zakresu technologii których używamy takich ...', 'https://yt3.ggpht.com/-CrjIydI6caM/AAAAAAAAAAI/AAAAAAAAAAA/slNkjTDm_a8/s88-c-k-no-mo-rj-c0xffffff/photo.jpg', '2018-05-30 00:30:14', '2018-05-30 00:30:55'),
(3, 'SPInkafilmstudio', 'BLOK EKIPA, KOŃ RAFAŁ, ADWERSARZE i BIRD BRAIN. Tylko na kanale SPInka Film Studio masz szansę sprawdzić swoje poczucie humoru. Subskrybujcie ...', 'https://yt3.ggpht.com/-k3uWnxXm9Zw/AAAAAAAAAAI/AAAAAAAAAAA/ng6QiLXkD-s/s88-c-k-no-mo-rj-c0xffffff/photo.jpg', '2018-05-30 00:33:20', '2018-05-30 00:35:38'),
(4, 'Rafał Pacześ', 'Jedyny oficjalny kanał Rafała Paczesia.', 'https://yt3.ggpht.com/-XFMEwrQvuJI/AAAAAAAAAAI/AAAAAAAAAAA/Cdoh0m8ktoM/s88-c-k-no-mo-rj-c0xffffff/photo.jpg', '2018-05-30 00:33:46', '2018-05-30 00:35:47'),
(5, 'KręciołaTV', 'http://kreciola.tv/ Videoblog Jurka Owsiaka, muza z Przystanków Woodstock, wywiady z artystami, promocja młodych zespołów i programy LIVE!', 'https://yt3.ggpht.com/-LG6ihQq-OI8/AAAAAAAAAAI/AAAAAAAAAAA/zGML2qfXKnc/s88-c-k-no-mo-rj-c0xffffff/photo.jpg', '2018-05-30 00:34:11', '2018-05-30 00:35:51'),
(6, 'thekooksofficial', 'Pre-order our new album, Let\'s Go Sunshine, at https://thekooks.lnk.to/letsgosunshine!', 'https://yt3.ggpht.com/-njJAsHNvInk/AAAAAAAAAAI/AAAAAAAAAAA/o1MCWZkZoX8/s88-c-k-no-mo-rj-c0xffffff/photo.jpg', '2018-05-30 00:35:03', '2018-05-30 00:36:01');

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `movie`
--

CREATE TABLE `movie` (
  `id` int(11) NOT NULL,
  `channel_id` int(11) DEFAULT NULL,
  `name` longtext COLLATE utf8_unicode_ci NOT NULL,
  `link` longtext COLLATE utf8_unicode_ci NOT NULL,
  `thumbnail` longtext COLLATE utf8_unicode_ci NOT NULL,
  `views` int(11) DEFAULT NULL,
  `description` longtext COLLATE utf8_unicode_ci NOT NULL,
  `fullDescription` longtext COLLATE utf8_unicode_ci NOT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Zrzut danych tabeli `movie`
--

INSERT INTO `movie` (`id`, `channel_id`, `name`, `link`, `thumbnail`, `views`, `description`, `fullDescription`, `createdAt`, `updatedAt`) VALUES
(26, 2, 'Lekcja 16 - Analiza danych z serwisu REST', 'https://www.youtube.com/embed/RvPCA6ZXWDY', 'https://i.ytimg.com/vi/RvPCA6ZXWDY/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:55', '2018-05-30 00:30:55'),
(27, 2, 'Lekcja 17 - Poprawa modeli oraz metod', 'https://www.youtube.com/embed/Q7NuL62UU5g', 'https://i.ytimg.com/vi/Q7NuL62UU5g/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:56', '2018-05-30 00:30:56'),
(28, 2, 'Lekcja 13 - Zadanie domowe - Rozwiązanie', 'https://www.youtube.com/embed/9Y2uZqC7Mok', 'https://i.ytimg.com/vi/9Y2uZqC7Mok/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:56', '2018-05-30 00:30:56'),
(29, 2, 'Lekcja 14 - Małe sprzątanie (Page, ObservableCollection itd)', 'https://www.youtube.com/embed/umEnMkabLgI', 'https://i.ytimg.com/vi/umEnMkabLgI/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:56', '2018-05-30 00:30:56'),
(30, 2, 'Lekcja 18 - Zadanie domowe :)', 'https://www.youtube.com/embed/DMV2Sq9IJ9g', 'https://i.ytimg.com/vi/DMV2Sq9IJ9g/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:57', '2018-05-30 00:30:57'),
(31, 2, 'Lekcja 15 - Strona detali', 'https://www.youtube.com/embed/VNKpl48PX1c', 'https://i.ytimg.com/vi/VNKpl48PX1c/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:57', '2018-05-30 00:30:57'),
(32, 2, 'Lekcja 12 - Praca nad UI', 'https://www.youtube.com/embed/qErRF0i-3Jg', 'https://i.ytimg.com/vi/qErRF0i-3Jg/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:57', '2018-05-30 00:30:57'),
(33, 2, 'Lekcja 09 - Obsługa błędów i słodsze metody', 'https://www.youtube.com/embed/2pF3EoQ1fcw', 'https://i.ytimg.com/vi/2pF3EoQ1fcw/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:58', '2018-05-30 00:30:58'),
(34, 2, 'Lekcja 10 - Krótko o programie Fiddler', 'https://www.youtube.com/embed/XIXMTJh4Efg', 'https://i.ytimg.com/vi/XIXMTJh4Efg/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:58', '2018-05-30 00:30:58'),
(35, 2, 'Lekcja 08 - Formatka wyszukiwania', 'https://www.youtube.com/embed/IxvboeSPIrE', 'https://i.ytimg.com/vi/IxvboeSPIrE/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:59', '2018-05-30 00:30:59'),
(36, 2, 'Lekcja 11 - Podejście reaktywne', 'https://www.youtube.com/embed/X3IpM2jokQo', 'https://i.ytimg.com/vi/X3IpM2jokQo/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:59', '2018-05-30 00:30:59'),
(37, 2, 'Lekcja 02 - Dokumentacja', 'https://www.youtube.com/embed/b4tgs6-Oq-o', 'https://i.ytimg.com/vi/b4tgs6-Oq-o/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:30:59', '2018-05-30 00:30:59'),
(38, 2, 'Lekcja 01 - Wstęp', 'https://www.youtube.com/embed/EpZe4bLWzpw', 'https://i.ytimg.com/vi/EpZe4bLWzpw/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:00', '2018-05-30 00:31:00'),
(39, 2, 'Lekcja 04 - Pobieranie danych z API', 'https://www.youtube.com/embed/WIeOiBdOdCI', 'https://i.ytimg.com/vi/WIeOiBdOdCI/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:00', '2018-05-30 00:31:00'),
(40, 2, 'Lekcja 05 - Przetwarzanie wyniku z API', 'https://www.youtube.com/embed/rNTi4gM4688', 'https://i.ytimg.com/vi/rNTi4gM4688/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:00', '2018-05-30 00:31:00'),
(41, 2, 'Lekcja 06 - Testowe wyświetlanie wyników', 'https://www.youtube.com/embed/f3ZUjOIGvRw', 'https://i.ytimg.com/vi/f3ZUjOIGvRw/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:00', '2018-05-30 00:31:00'),
(42, 2, 'Lekcja 03 - Projekt i Struktura programu', 'https://www.youtube.com/embed/rbPUtuizees', 'https://i.ytimg.com/vi/rbPUtuizees/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:01', '2018-05-30 00:31:01'),
(43, 2, 'Lekcja 07 - Podsumowanie obecnej pracy', 'https://www.youtube.com/embed/BXXfT0j4nH0', 'https://i.ytimg.com/vi/BXXfT0j4nH0/default.jpg', NULL, '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami ...', '\"Robim program\" to kurs w którym rozpoczniecie przygodę z prawdziwą aplikacją. Od dokumentacji do finalnego produktu z wszystkimi pomyłkami, poprawkami i złymi praktykami. Zapraszamy serdecznie.\n\nZnajdziecie nas:\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:01', '2018-05-30 00:31:01'),
(44, 2, 'Lekcja 18 - To już jest koniec ...', 'https://www.youtube.com/embed/klZPp2qxIkI', 'https://i.ytimg.com/vi/klZPp2qxIkI/default.jpg', NULL, 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób ...', 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób przedstawić wszystkie podstawowe aspekty programowania. W miarę możliwości pokażemy też \"dobre praktyki\" programowania. Zapraszamy serdecznie.\n\nZnajdziecie nas:\nGithub (kod źródłowy): https://goo.gl/7UFbPv\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:02', '2018-05-30 00:31:02'),
(45, 2, 'Lekcja 17 - Instrukcje złożone (część 02)', 'https://www.youtube.com/embed/lcne6mqll_M', 'https://i.ytimg.com/vi/lcne6mqll_M/default.jpg', NULL, 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób ...', 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób przedstawić wszystkie podstawowe aspekty programowania. W miarę możliwości pokażemy też \"dobre praktyki\" programowania. Zapraszamy serdecznie.\n\nZnajdziecie nas:\nGithub (kod źródłowy): https://goo.gl/7UFbPv\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:02', '2018-05-30 00:31:02'),
(46, 2, 'Lekcja 16 - Metody', 'https://www.youtube.com/embed/tOeER4nw3Iw', 'https://i.ytimg.com/vi/tOeER4nw3Iw/default.jpg', NULL, 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób ...', 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób przedstawić wszystkie podstawowe aspekty programowania. W miarę możliwości pokażemy też \"dobre praktyki\" programowania. Zapraszamy serdecznie.\n\nZnajdziecie nas:\nGithub (kod źródłowy): https://goo.gl/7UFbPv\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:02', '2018-05-30 00:31:02'),
(47, 2, 'Lekcja 14 - Klasy (część 01)', 'https://www.youtube.com/embed/I4z2-m3LA1w', 'https://i.ytimg.com/vi/I4z2-m3LA1w/default.jpg', NULL, 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób ...', 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób przedstawić wszystkie podstawowe aspekty programowania. W miarę możliwości pokażemy też \"dobre praktyki\" programowania. Zapraszamy serdecznie.\n\nZnajdziecie nas:\nGithub (kod źródłowy): https://goo.gl/7UFbPv\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:03', '2018-05-30 00:31:03'),
(48, 2, 'Lekcja 15 - Klasy (część 02)', 'https://www.youtube.com/embed/YZHoQ6fjQ_A', 'https://i.ytimg.com/vi/YZHoQ6fjQ_A/default.jpg', NULL, 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób ...', 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób przedstawić wszystkie podstawowe aspekty programowania. W miarę możliwości pokażemy też \"dobre praktyki\" programowania. Zapraszamy serdecznie.\n\nZnajdziecie nas:\nGithub (kod źródłowy): https://goo.gl/7UFbPv\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:03', '2018-05-30 00:31:03'),
(49, 2, 'Lekcja 11 - Instrukcje złożone (część 01)', 'https://www.youtube.com/embed/trCFPdhtqJQ', 'https://i.ytimg.com/vi/trCFPdhtqJQ/default.jpg', NULL, 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób ...', 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób przedstawić wszystkie podstawowe aspekty programowania. W miarę możliwości pokażemy też \"dobre praktyki\" programowania. Zapraszamy serdecznie.\n\nZnajdziecie nas:\nGithub (kod źródłowy): https://goo.gl/7UFbPv\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:03', '2018-05-30 00:31:03'),
(50, 2, 'Lekcja 12 - Kolekcje', 'https://www.youtube.com/embed/Tiu6q_4f82s', 'https://i.ytimg.com/vi/Tiu6q_4f82s/default.jpg', NULL, 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób ...', 'Kurs \"Podstawy programowania w języku C#\" został przygotowany z myślą o nowicjuszach w programowaniu. Postaramy się w jak najbardziej klarowny sposób przedstawić wszystkie podstawowe aspekty programowania. W miarę możliwości pokażemy też \"dobre praktyki\" programowania. Zapraszamy serdecznie.\n\nZnajdziecie nas:\nGithub (kod źródłowy): https://goo.gl/7UFbPv\n\nFacebook: https://goo.gl/IfQrcU\nTwitter: https://goo.gl/OizAaS\nTwitch TV: https://goo.gl/7vJ6oC\n\nWWW: https://goo.gl/bEZqP3 - strona domowa firmy Impact IT\nBlog: https://goo.gl/kFvE5r - nasz blog o kursach (wieczna alpha)', '2018-05-30 00:31:04', '2018-05-30 00:31:04'),
(51, 3, 'BLOK EKIPA (136), HAIER', 'https://www.youtube.com/embed/c3FD45AKrKY', 'https://i.ytimg.com/vi/c3FD45AKrKY/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 136. odcinek serialu BLOK EKIPA! Zobacz koniecznie gościnnego vloga Spejsona dla Ekipy Haier: ...', 'SPInka Film Studio zaprasza na premierowy 136. odcinek serialu BLOK EKIPA!  Zobacz koniecznie gościnnego vloga Spejsona dla Ekipy Haier: https://www.youtube.com/watch?v=sqeRPrlfo_A&feature=youtu.be\n\nKonkursy: http://www.wygrajlodowke.pl/\n\nFilmik z poprzedniej akcji, który oglądał Wojtas: https://www.youtube.com/watch?v=vY6FtrQx8es&list=PLylCMfmHrMoY-2BItgG9vBWP6xGv0W75D\n\nNowa lodówka Spejsona: http://www.haier.com/pl/produkty/chlodnictwo/side-by-side/htf-610dm7.shtml\n\nSubskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl', '2018-05-30 00:35:39', '2018-05-30 00:35:39'),
(52, 3, 'EGZORCYSTA 2 - DEMONY SMOGU odc. 1 - PREMIERA!', 'https://www.youtube.com/embed/uJi4hDIvTo8', 'https://i.ytimg.com/vi/uJi4hDIvTo8/default.jpg', 1, 'Premierowy odcinek drugiego sezonu EGZORCYSTY w reż. Bartosza Walaszka wyjątkowo na kanale SPInki Film Studio! Po drugi sezon Egzorcysty wbijaj na ...', 'Premierowy odcinek drugiego sezonu EGZORCYSTY w reż. Bartosza Walaszka wyjątkowo na kanale SPInki Film Studio! Po drugi sezon Egzorcysty wbijaj na SHOWMAX.COM. Nowy odcinek co czwartek!', '2018-05-30 00:35:39', '2018-05-30 00:44:47'),
(53, 3, 'EGZORCYSTA SEZON 2 - PREMIERA 24 MAJA SHOWMAX!', 'https://www.youtube.com/embed/sPgflwP8leQ', 'https://i.ytimg.com/vi/sPgflwP8leQ/default.jpg', NULL, 'Już 24 maja nowy sezon Egzorcysty na SHOWMAX! Premierowy odcinek będziecie mogli wyjątkowo obejrzeć na kanale SPInki! Kolejne co tydzień na ...', 'Już 24 maja nowy sezon Egzorcysty na SHOWMAX! Premierowy odcinek będziecie mogli wyjątkowo obejrzeć na kanale SPInki! Kolejne co tydzień na SHOWMAX!', '2018-05-30 00:35:39', '2018-05-30 00:35:39'),
(54, 3, 'BLOK EKIPA (135), DUCH SZERSZENIA', 'https://www.youtube.com/embed/w8S4hCf_CAE', 'https://i.ytimg.com/vi/w8S4hCf_CAE/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 135. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 135. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl', '2018-05-30 00:35:40', '2018-05-30 00:35:40'),
(55, 3, 'BLOK EKIPA (134), WYPRAWA NA TARCHOMIN', 'https://www.youtube.com/embed/lxyaj98mp6k', 'https://i.ytimg.com/vi/lxyaj98mp6k/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 134. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 134. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl', '2018-05-30 00:35:40', '2018-05-30 00:35:40'),
(56, 3, 'BLOK EKIPA (133) - WIESŁAW NA GIGANCIE', 'https://www.youtube.com/embed/BzQ1grygcrY', 'https://i.ytimg.com/vi/BzQ1grygcrY/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 133. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 133. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl', '2018-05-30 00:35:40', '2018-05-30 00:35:40'),
(57, 3, 'BLOK EKIPA (132), LESBIJKI', 'https://www.youtube.com/embed/q9sglYVotSA', 'https://i.ytimg.com/vi/q9sglYVotSA/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 132. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 132. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl', '2018-05-30 00:35:41', '2018-05-30 00:35:41'),
(58, 3, 'BLOK EKIPA (131), KRÓLOWIE ŻYCIA', 'https://www.youtube.com/embed/RIYKW_NuJ1c', 'https://i.ytimg.com/vi/RIYKW_NuJ1c/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 131. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 131. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl', '2018-05-30 00:35:41', '2018-05-30 00:35:41'),
(59, 3, 'BLOK EKIPA (130), POSZUKIWACZE ZAGINIONEGO SZMALU', 'https://www.youtube.com/embed/0CO3o0IOkaE', 'https://i.ytimg.com/vi/0CO3o0IOkaE/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 130. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 130. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:41', '2018-05-30 00:35:41'),
(60, 3, 'BLOK EKIPA (129), MUAY THAI', 'https://www.youtube.com/embed/OVHAUxJzios', 'https://i.ytimg.com/vi/OVHAUxJzios/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 129. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 129. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:42', '2018-05-30 00:35:42'),
(61, 3, 'SPEJSONVLOG - PORADY WALENTYNKOWE', 'https://www.youtube.com/embed/v5BVg0YIpYo', 'https://i.ytimg.com/vi/v5BVg0YIpYo/default.jpg', NULL, 'Elo ziomeczki! Spejson ponownie zabrał głos w dniu święta zakochanych. Obejrzyjcie koniecznie! Lajki i udostępnienia mile widziane! INST @spejsonvlog FB ...', 'Elo ziomeczki! Spejson ponownie zabrał głos w dniu święta zakochanych. Obejrzyjcie koniecznie! Lajki i udostępnienia mile widziane!\n\nINST @spejsonvlog\nFB fb.com/spinka.blokekipa\nsklep: spinka.cupsell.pl', '2018-05-30 00:35:42', '2018-05-30 00:35:42'),
(62, 3, 'BLOK EKIPA (128), DRAJWER', 'https://www.youtube.com/embed/nWRFbMA--7Q', 'https://i.ytimg.com/vi/nWRFbMA--7Q/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 128. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 128. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:42', '2018-05-30 00:35:42'),
(63, 3, 'BLOK EKIPA (127), FAJTER', 'https://www.youtube.com/embed/3nsMSHAOt2E', 'https://i.ytimg.com/vi/3nsMSHAOt2E/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 127. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 127. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:43', '2018-05-30 00:35:43'),
(64, 3, 'EGZORCYSTA - Finał sezonu!', 'https://www.youtube.com/embed/xU0HwiZqOsI', 'https://i.ytimg.com/vi/xU0HwiZqOsI/default.jpg', NULL, 'Zapraszamy Was do obejrzenia finałowego odcinka Egzorcysty na SHOWMAXIE! www.showmax.com.', 'Zapraszamy Was do obejrzenia finałowego odcinka Egzorcysty na SHOWMAXIE!\n\nwww.showmax.com', '2018-05-30 00:35:43', '2018-05-30 00:35:43'),
(65, 3, 'SPEJSONVLOG - POSTANOWIENIA NOWOROCZNE', 'https://www.youtube.com/embed/Y-TtUI8IRAs', 'https://i.ytimg.com/vi/Y-TtUI8IRAs/default.jpg', NULL, 'Elo ziomeczki! Wszystkiego dobrego w Nowym Roku. Zobaczcie koniecznie jakie postanowienia mają bohaterowie BLOK EKIPY! A już 22.01 nowy odcinek Blok ...', 'Elo ziomeczki! Wszystkiego dobrego w Nowym Roku. Zobaczcie koniecznie jakie postanowienia mają bohaterowie BLOK EKIPY! A już 22.01 nowy odcinek Blok Ekipy! Subskrybujcie kanał i dajcie się ponieść absurdowi.\n\nfb.com/spinka.blokekipa\ninst @spejsonvlog', '2018-05-30 00:35:43', '2018-05-30 00:35:43'),
(66, 3, 'BLOK EKIPA (126), MYJNIA', 'https://www.youtube.com/embed/q_tPvFE5gGU', 'https://i.ytimg.com/vi/q_tPvFE5gGU/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 126. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 126. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:44', '2018-05-30 00:35:44'),
(67, 3, 'SPEJSONVLOG - ŻYCZENIA ŚWIĄTECZNE', 'https://www.youtube.com/embed/si9SyPBgiVc', 'https://i.ytimg.com/vi/si9SyPBgiVc/default.jpg', NULL, 'Elo ziomeczki! Życzymy Wam wraz ze Spejsonem średnich świąt! Wszystkiego dobrego!', 'Elo ziomeczki! Życzymy Wam wraz ze Spejsonem średnich świąt! Wszystkiego dobrego!', '2018-05-30 00:35:44', '2018-05-30 00:35:44'),
(68, 3, 'EGZORCYSTA (teaser 10 odcinka)', 'https://www.youtube.com/embed/pQ5Ju-pCJIk', 'https://i.ytimg.com/vi/pQ5Ju-pCJIk/default.jpg', NULL, 'Elo ziomeczki! Na SHOWMAXIE właśnie straszy nowy odcinek EGZORCYSTY! Zobaczcie koniecznie - www.showmax.com.', 'Elo ziomeczki! Na SHOWMAXIE właśnie straszy nowy odcinek EGZORCYSTY! Zobaczcie koniecznie - www.showmax.com', '2018-05-30 00:35:44', '2018-05-30 00:35:44'),
(69, 3, 'DRUNK HISTORY - SPEJSON', 'https://www.youtube.com/embed/JZg0jp1ca5E', 'https://i.ytimg.com/vi/JZg0jp1ca5E/default.jpg', NULL, 'Elo ziomeczki! Razem z Comedy-Central serwujemy przedswiateczny prezent dla naszych fanów - odcinek DRUNK HISTORY z udziałem Spejsona. A już w ...', 'Elo ziomeczki! Razem z Comedy-Central serwujemy przedswiateczny prezent dla naszych fanów - odcinek DRUNK HISTORY z udziałem Spejsona. A już w poniedziałek nowy odcinek BLOK EKIPY! Subskrybujcie kanał SPInki Film Studio i dajcie się ponieść absurdowi!  Średnich świąt wszystkim!', '2018-05-30 00:35:45', '2018-05-30 00:35:45'),
(70, 3, 'BLOK EKIPA (125), WŚCIEKŁY WĄŻ', 'https://www.youtube.com/embed/nd9licEki1s', 'https://i.ytimg.com/vi/nd9licEki1s/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 125. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 125. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:45', '2018-05-30 00:35:45'),
(71, 3, 'BLOK EKIPA (124), ZAPASY W KISIELU', 'https://www.youtube.com/embed/LVW7qPyF6lA', 'https://i.ytimg.com/vi/LVW7qPyF6lA/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 124. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 124. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. \n\nAplikacja do pobrania: https://play.google.com/store/apps/details?id=com.beamup.beamup&hl=pl\n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:45', '2018-05-30 00:35:45'),
(72, 3, 'EGZORCYSTA (teaser 5 odcinka)', 'https://www.youtube.com/embed/batJ-zBlAHI', 'https://i.ytimg.com/vi/batJ-zBlAHI/default.jpg', NULL, 'Elo ziomeczki! Na SHOWMAXIE właśnie straszy nowy odcinek EGZORCYSTY! Zobaczcie koniecznie - www.showmax.com.', 'Elo ziomeczki! Na SHOWMAXIE właśnie straszy nowy odcinek EGZORCYSTY! Zobaczcie koniecznie - www.showmax.com', '2018-05-30 00:35:46', '2018-05-30 00:35:46'),
(73, 3, 'BLOK EKIPA (123), PALETA KILLER', 'https://www.youtube.com/embed/Res9TLU3HzI', 'https://i.ytimg.com/vi/Res9TLU3HzI/default.jpg', NULL, 'SPInka Film Studio zaprasza na premierowy 123. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi!', 'SPInka Film Studio zaprasza na premierowy 123. odcinek serialu BLOK EKIPA! Subskrybujcie kanał SPInki FIlm Studio i dajcie się ponieść absurdowi! Lajki i udostępnienia mile widziane. Suplementy: http://www.sfd.pl/sklep/Berserk_Labs_Ekipa-p66600436.html\n\nfb: fb.com/spinka.blokekipa\ninst @spejsonvlog\ngadzety: spinka.cupsell.pl oraz www.dzikirejon.pl', '2018-05-30 00:35:46', '2018-05-30 00:35:46'),
(74, 3, 'SPEJSONVLOG - JAK PRZYGOTOWAĆ FURĘ NA SPRZEDAŻ?', 'https://www.youtube.com/embed/3qj-RbPZZC8', 'https://i.ytimg.com/vi/3qj-RbPZZC8/default.jpg', NULL, 'SPInka Film Studio zaprasza do obejrzenia najnowszego vloga Spejsona. Subskrybujcie kanal i dajcie sie poniesc absurdowi! FB.COM/SPINKA.BLOKEKIPA ...', 'SPInka Film Studio zaprasza do obejrzenia najnowszego vloga Spejsona.\n\nSubskrybujcie kanal i dajcie sie poniesc absurdowi! \n\nFB.COM/SPINKA.BLOKEKIPA\ninst @spejsonvlog\nkoszulki spinka.cupsell.pl\nnaklejki - www.dzikirejon.pl', '2018-05-30 00:35:46', '2018-05-30 00:35:46'),
(75, 3, 'EGZORCYSTA (drugi trailer)', 'https://www.youtube.com/embed/RFAtvA1cu7o', 'https://i.ytimg.com/vi/RFAtvA1cu7o/default.jpg', NULL, 'Już od 1 listopada na showmaxie nowy serial w reżyserii Bartosza Walaszka. Nie możecie tego przegapić, bo będzie strasznie... śmiesznie! więcej na: ...', 'Już od 1 listopada na showmaxie nowy serial w reżyserii Bartosza Walaszka. Nie możecie tego przegapić, bo będzie strasznie... śmiesznie!\n\nwięcej na: www.showmax.com', '2018-05-30 00:35:47', '2018-05-30 00:35:47'),
(76, 4, 'Rafał Pacześ \"BANG\"', 'https://www.youtube.com/embed/i8OYerdcmCc', 'https://i.ytimg.com/vi/i8OYerdcmCc/default.jpg', 1, 'Monolog pt. \"BANG\" z projektu Grupa Trzymająca Mikrofon (Kacper Ruciński, Łukasz \"Lotek\" Lodkowski i Rafał Pacześ. Lublin 5 marca 2018 FB: ...', 'Monolog pt. \"BANG\" z projektu Grupa Trzymająca Mikrofon (Kacper Ruciński, Łukasz \"Lotek\" Lodkowski i Rafał Pacześ.\nLublin 5 marca 2018\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:48', '2018-05-30 00:44:41'),
(77, 4, 'Rafał Pacześ \"Zaczynam Rozumieć\"', 'https://www.youtube.com/embed/M4ANTgkixNE', 'https://i.ytimg.com/vi/M4ANTgkixNE/default.jpg', NULL, 'Rafał Pacześ w swoim solowym programie \"Zaczynam Rozumieć\" (2016/17r) FB: https://www.facebook.com/rafal.paczes.comedy/ STAND UP: ...', 'Rafał Pacześ w swoim solowym programie \"Zaczynam Rozumieć\" (2016/17r)\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:48', '2018-05-30 00:35:48'),
(78, 4, 'Rafał Pacześ zwiastun \"Zaczynam Rozumieć\"', 'https://www.youtube.com/embed/Jr49lZ3YyGM', 'https://i.ytimg.com/vi/Jr49lZ3YyGM/default.jpg', NULL, 'Zwiastun solowego programu Rafała Paczesia pt. \"Zaczynam Rozumieć\" zarejestrowany w łódzkiej klubokawiarni Scenografia, cały materiał już 20 sierpnia ...', 'Zwiastun solowego programu Rafała Paczesia pt. \"Zaczynam Rozumieć\" zarejestrowany w łódzkiej klubokawiarni Scenografia, cały materiał już 20 sierpnia :)\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:48', '2018-05-30 00:35:48'),
(79, 4, 'Rafał Pacześ zaprasza na premierę Mixtape \"How To Be Chill\" - Dj Cube', 'https://www.youtube.com/embed/Zo2YdB0hi1E', 'https://i.ytimg.com/vi/Zo2YdB0hi1E/default.jpg', NULL, 'zapraszam na premierę Dj Cube Mixtape \"How To Be Chill\" FB: https://www.facebook.com/rafal.paczes.comedy/ STAND UP: ...', 'zapraszam na premierę Dj Cube Mixtape \"How To Be Chill\"\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:49', '2018-05-30 00:35:49'),
(80, 4, 'Rafał Pacześ wspiera Piotrka Szumowskiego', 'https://www.youtube.com/embed/gbyQa4Vbhc4', 'https://i.ytimg.com/vi/gbyQa4Vbhc4/default.jpg', NULL, 'Piotr Szumowski chce wybrać się w podróż dookoła świata. FB: https://www.facebook.com/rafal.paczes.comedy/ STAND UP: ...', 'Piotr Szumowski chce wybrać się w podróż dookoła świata.\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:49', '2018-05-30 00:35:49'),
(81, 4, 'Suchar Challenge czyli Rafał Pacześ zaprasza na 31 PAKĘ', 'https://www.youtube.com/embed/TtYt22YlCes', 'https://i.ytimg.com/vi/TtYt22YlCes/default.jpg', NULL, 'Rafał Pacześ w swoim stylu zaprasza na finały 31 PAKI. FB: https://www.facebook.com/rafal.paczes.comedy/ STAND UP: ...', 'Rafał Pacześ w swoim stylu zaprasza na finały 31 PAKI.\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:50', '2018-05-30 00:35:50'),
(82, 4, 'Mistrz Uwodzenia', 'https://www.youtube.com/embed/dA3ZBq2ktLU', 'https://i.ytimg.com/vi/dA3ZBq2ktLU/default.jpg', NULL, 'Cenne rady jak uwodzić i jak postępować z kobietami- Rafał Paciesz FB: https://www.facebook.com/rafal.paczes.comedy/ STAND UP: ...', 'Cenne rady jak uwodzić i jak postępować z kobietami- Rafał Paciesz\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:50', '2018-05-30 00:35:50'),
(83, 4, 'Mistrz sprzedaży', 'https://www.youtube.com/embed/_S5ErkAak-c', 'https://i.ytimg.com/vi/_S5ErkAak-c/default.jpg', NULL, 'Cenne rady, jak poradzić sobie w handlu, jak prowadzić własną firmę. FB: https://www.facebook.com/rafal.paczes.comedy/ STAND UP: ...', 'Cenne rady, jak poradzić sobie w handlu, jak prowadzić własną firmę.\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:50', '2018-05-30 00:35:50'),
(84, 4, 'Rafał Pacześ Stand up', 'https://www.youtube.com/embed/f-5kujSar54', 'https://i.ytimg.com/vi/f-5kujSar54/default.jpg', NULL, 'Support \"Bez cenzury\" - po prostu o kiblu na półpiętrze i wersalce :) 04.2013 FB: https://www.facebook.com/rafal.paczes.comedy/ STAND UP: ...', 'Support \"Bez cenzury\" - po prostu o kiblu na półpiętrze i wersalce :) 04.2013\n\n????FB: https://www.facebook.com/rafal.paczes.comedy/\n???? STAND UP: https://www.youtube.com/playlist?list=PLtEcs74AUXfp9E-0fQUdaQtYpzIWBjhgY', '2018-05-30 00:35:51', '2018-05-30 00:35:51'),
(85, 5, 'Lao Che - Zombi #Woodstock2014', 'https://www.youtube.com/embed/M97SdtrIE44', 'https://i.ytimg.com/vi/M97SdtrIE44/default.jpg', NULL, 'Występ zespołu Lao Che na 20. Przystanku Woodstock zgromadził pod sceną spory tłum - zobaczcie i posłuchajcie kolejnego fragmentu ich koncertu!', 'Występ zespołu Lao Che na 20. Przystanku Woodstock zgromadził pod sceną spory tłum - zobaczcie i posłuchajcie kolejnego fragmentu ich koncertu!', '2018-05-30 00:35:52', '2018-05-30 00:35:52'),
(86, 5, 'Shaka Ponk - Morir Cantando #Woodstock2015', 'https://www.youtube.com/embed/fUL6sDRP4_8', 'https://i.ytimg.com/vi/fUL6sDRP4_8/default.jpg', NULL, 'Shaka Ponk to kapela łączącą w swojej muzyce elementy ciężkiego rocka, industrialu, hip-hopu i funky. Do tego muzycy przyjechali z inscenizacją jakiej nie ...', 'Shaka Ponk to kapela łączącą w swojej muzyce elementy ciężkiego rocka, industrialu, hip-hopu i funky. Do tego muzycy przyjechali z inscenizacją jakiej nie było Przystanku Woodstock chyba nigdy. W efekcie występ świetnie wyglądał i wspaniale wybrzmiał. Z resztą sprawdźcie sami!  \n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:52', '2018-05-30 00:35:52'),
(87, 5, 'Organek - retransmisja koncertu!  #Woodstock2015', 'https://www.youtube.com/embed/Ph4nNml9GwU', 'https://i.ytimg.com/vi/Ph4nNml9GwU/default.jpg', NULL, 'ØRGANEK na Dużą Scenę trafił dzięki Eliminacjom do Przystanku Woodstock. To klasyczne w brzmieniu, nowatorskie w formie vintage, rockowe power trio ...', 'ØRGANEK na Dużą Scenę trafił dzięki Eliminacjom do Przystanku Woodstock. To klasyczne w brzmieniu, nowatorskie w formie vintage, rockowe power trio wspomagane organami Vox\'a. Wyraziste, błyskotliwie opisujące teraźniejszość teksty osadzone w pełnej cytatów i historycznych odniesień muzyce, a także niezwykła ekspresja sceniczna stanowią o wartości zespołu powołanego do życia w 2013 roku przez jego lidera, autora tekstów i kompozycji, gitarzystę i wokalistę - Tomasza Organka.\n\nPodczas koncertu na pewno nie zabraknie największych przebojów Organka, takich jak: „Głupi ja”, „O, matko”, \"Kate Moss\" - zapraszamy na retransmisję koncertu! \n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:53', '2018-05-30 00:35:53'),
(88, 5, 'Akurat - Dyskoteka gra', 'https://www.youtube.com/embed/EPjCRPWw2JE', 'https://i.ytimg.com/vi/EPjCRPWw2JE/default.jpg', NULL, 'Wracamy do słonecznych Żar i VII Przystanku Woodstock - zachęcamy do pobujania się radośnie razem z zespołem Akurat. Ktoś z Was pamięta ten koncert?', 'Wracamy do słonecznych Żar i VII Przystanku Woodstock - zachęcamy do pobujania się radośnie razem z zespołem Akurat. Ktoś z Was pamięta ten koncert? \n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:53', '2018-05-30 00:35:53'),
(89, 5, '#43 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/qN_v8F3MeBo', 'https://i.ytimg.com/vi/qN_v8F3MeBo/default.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo! #43 Kręciołowa Dziesiątka a w niej: Akurat - Dyskoteka gra Nine Circle - Games People ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo! #43 Kręciołowa Dziesiątka a w niej:\nAkurat - Dyskoteka gra\nNine Circle - Games People Play\nJelonek - Mana Mana\nKSU - Na krawędzi snu\nLao Che - Zombi\nMy Riot - Sen\nOlej - Skinowski\nPogodno - Jak Ty się czujesz\nSjhaka Ponk - Morir Cantando\nthe Bill - Piposenka dla żołnierza\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:53', '2018-05-30 00:35:53'),
(90, 5, 'Retransmisja ASP - prof. Zbigniew Lew - Starowicz #Woodstock2013', 'https://www.youtube.com/embed/oOZfVpqL8_A', 'https://i.ytimg.com/vi/oOZfVpqL8_A/default.jpg', NULL, 'Zapraszamy do obejrzenia spotkania z prof. Zbigniewem Lwem - Starowiczem, które można nazwać: \"wszystko, co chcecie wiedzieć o seksie, ale boicie się ...', 'Zapraszamy do obejrzenia spotkania z prof. Zbigniewem Lwem - Starowiczem, które można nazwać: \"wszystko, co chcecie wiedzieć o seksie, ale boicie się zapytać\". \n\nRetransmisja wystartuje we wtorek (22.05) o godz. 16:00. \n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:54', '2018-05-30 00:35:54'),
(91, 5, 'Za nami poznański półfinał Eliminacji 24. Pol\'and\'Rock Festivalu!', 'https://www.youtube.com/embed/zxtdx9-OKgY', 'https://i.ytimg.com/vi/zxtdx9-OKgY/default.jpg', NULL, 'Znamy kolejnych finalistów Eliminacji! Decyzją jurorów Two Timer - otrzymał zaproszenie na Scenę Lecha, Łydka Grubasa - otrzymali zaproszenie na Małą ...', 'Znamy kolejnych finalistów Eliminacji! Decyzją jurorów Two Timer - otrzymał zaproszenie na Scenę Lecha, Łydka Grubasa - otrzymali zaproszenie na Małą Scenę, Opus Magnum, Neuoberschlesien i OHO!KOKO - przechodzą do Finału Eliminacji i 30 czerwca w Warszawie powalczą o zaproszenie na sceny Najpiękniejszego Festiwalu Świata. \n\nJak było na drugim Półfinale Eliminacji do 24. Pol\'and\'Rock? Sami zobaczcie!\n\n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:54', '2018-05-30 00:35:54'),
(92, 5, 'Retransmisja koncertu Sweet Noise z Woodstock 2001', 'https://www.youtube.com/embed/MUQOb50lIDk', 'https://i.ytimg.com/vi/MUQOb50lIDk/default.jpg', NULL, 'Zaglądamy do naszego muzycznego archiwum by wspólnie posłuchać koncertu Sweet Noise Band, który odbył się na Przystanku Woodstock w 2001 roku!', 'Zaglądamy do naszego muzycznego archiwum by wspólnie posłuchać koncertu Sweet Noise Band, który odbył się na Przystanku Woodstock w 2001 roku!\n\nKoncert w całości puścimy na naszym YouTube w czwartek (17.05) o godz. 18:00.\n\n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:54', '2018-05-30 00:35:54'),
(93, 5, '#42 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/9yxHLYKk5Eg', 'https://i.ytimg.com/vi/9yxHLYKk5Eg/default.jpg', NULL, 'Oto ona - #42 Kręciołowa Dziesiątka! Jakich piosenek słucha się najlepiej, kiedy za oknem pogoda barowa? Wasze propozycje: Budka Suflera - Jest taki ...', 'Oto ona - #42 Kręciołowa Dziesiątka! Jakich piosenek słucha się najlepiej, kiedy za oknem pogoda barowa? Wasze propozycje: \n\nBudka Suflera - Jest taki samotny dom\nCarrantuohill - Silver\nComa - Skaczemy\nDamian Marley - Could you be love\nDomowe Melodie - Techno\nJuliette Lewis - Devil knows\nKuba Płucisz - Nie uciekaj\nPiersi - Żośka\nRaz Dwa Trzy - Jutro możemy być szczęśliwi\nShaggy - Boombastic\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:55', '2018-05-30 00:35:55'),
(94, 5, 'Retransmiaja spotkania na ASP z Andrzejem Wajdą', 'https://www.youtube.com/embed/sMcSLb2nywA', 'https://i.ytimg.com/vi/sMcSLb2nywA/default.jpg', NULL, '\"Andrzeja Wajdę oraz jego przeuroczą i bardzo ciepłą małżonkę – Krystynę Zachwatowicz ściągnęliśmy na Festiwal przy okazji kręcenia przez niego filmu ...', '\"Andrzeja Wajdę oraz jego przeuroczą i bardzo ciepłą małżonkę – Krystynę Zachwatowicz ściągnęliśmy na Festiwal przy okazji kręcenia przez niego filmu „Katyń”. Film już był nakręcony, montowany i namawialiśmy Pana Andrzeja, aby kawałek był pokazany Woodstockowiczom. Filmu w końcu nie pokazaliśmy, ale za to rozmowa potoczyła się o całej, ogromnej twórczości Pana Andrzeja, o nim samym, o tym wszystkim, co wie każdy, i o tym co mogliśmy usłyszeć po raz pierwszy.\" \n\nJurek Owsiak\n\nZapraszamy do znalezienia chwili i wysłuchania całej rozmowy z Andrzejem Wajdą, które odbyło się na Przystanku Woodstock w 2010 roku - start retransmisji we storek (15.05) o godz. 16:00. \n\n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:55', '2018-05-30 00:35:55');
INSERT INTO `movie` (`id`, `channel_id`, `name`, `link`, `thumbnail`, `views`, `description`, `fullDescription`, `createdAt`, `updatedAt`) VALUES
(95, 5, 'The Hives - Go right ahead #Woodstock2016', 'https://www.youtube.com/embed/Sfvt9XSSDIY', 'https://i.ytimg.com/vi/Sfvt9XSSDIY/default.jpg', NULL, 'Dzisiaj słuchamy koncertu szwedzkiej, rockowej grupy The Hives! Ich występ okazał się wielką, pozytywną niespodzianką i przyciągnął tłumy. Z resztą ...', 'Dzisiaj słuchamy koncertu szwedzkiej, rockowej grupy The Hives! Ich występ okazał się wielką, pozytywną niespodzianką i przyciągnął tłumy. Z resztą zobaczcie sami! \n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:55', '2018-05-30 00:35:55'),
(96, 5, 'LemON - Myśl #Woodstock2017', 'https://www.youtube.com/embed/P6ZKEszCo1Q', 'https://i.ytimg.com/vi/P6ZKEszCo1Q/default.jpg', NULL, 'Na koncert LemOna czekało wiele osób, co widać po tłumnie zgromadzonej przed sceną publiczności. Jego występ wiele osób zapamięta na długo. Odpalajcie ...', 'Na koncert LemOna czekało wiele osób, co widać po tłumnie zgromadzonej przed sceną publiczności. Jego występ wiele osób zapamięta na długo. Odpalajcie i słuchajcie!\n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:56', '2018-05-30 00:35:56'),
(97, 5, 'Scena Nocna ASP - retransmisja koncertu Pawbeats Orchestra', 'https://www.youtube.com/embed/wfxwmEl7RPA', 'https://i.ytimg.com/vi/wfxwmEl7RPA/default.jpg', NULL, 'Pawbeats Orchestra to bardzo ciekawy projekt łączący rap, muzykę popularną oraz symfoniczną. Na jednej scenie wystąpiła m.in. orkiestra symfoniczna, ...', 'Pawbeats Orchestra to bardzo ciekawy projekt łączący rap, muzykę popularną oraz symfoniczną. Na jednej scenie wystąpiła m.in. orkiestra symfoniczna, wokaliści i raperzy. Co z tego wynikło? Przekonajcie się sami podczas naszej retransmisji - koncert w całości puścimy w czwartek (10.05) o godz. 18:00!\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:56', '2018-05-30 00:35:56'),
(98, 5, '#47 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/Fpyuv7U6BoQ', 'https://i.ytimg.com/vi/Fpyuv7U6BoQ/default_live.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami wybieracie!\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:57', '2018-05-30 00:35:57'),
(99, 5, '#48 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/p0UTfM0P-qc', 'https://i.ytimg.com/vi/p0UTfM0P-qc/default_live.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami wybieracie!\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:57', '2018-05-30 00:35:57'),
(100, 5, '#45 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/uPkLUMc-Li4', 'https://i.ytimg.com/vi/uPkLUMc-Li4/default_live.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami wybieracie!\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:57', '2018-05-30 00:35:57'),
(101, 5, '#46 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/pbZF4hx5Kqs', 'https://i.ytimg.com/vi/pbZF4hx5Kqs/default_live.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami wybieracie!\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:58', '2018-05-30 00:35:58'),
(102, 5, 'Ludzie Mili - Poeci', 'https://www.youtube.com/embed/R6fgG4V7HvQ', 'https://i.ytimg.com/vi/R6fgG4V7HvQ/default.jpg', NULL, 'Ludzie Mili to tak naprawdę Indios Bravos w odsłonie bluesowej, wokalistą tutaj również jest Gutek, w tym przypadku wspomagany jednak dodatkowo przez ...', 'Ludzie Mili to tak naprawdę Indios Bravos w odsłonie bluesowej, wokalistą tutaj również jest Gutek, w tym przypadku wspomagany jednak dodatkowo przez damski i męski wokal. \n\nPosłuchajcie i przypomnijcie sobie ich występ podczas 18. Przystanku Woodstock!\n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:58', '2018-05-30 00:35:58'),
(103, 5, '#41 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/J_LfvSod83k', 'https://i.ytimg.com/vi/J_LfvSod83k/default.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo - #41 Kręciołowa Dziesiątka: Dub Inc - Better run Habakuk - Rasta trans Lemon - Myśl ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo - #41 Kręciołowa Dziesiątka:\nDub Inc - Better run\nHabakuk - Rasta trans\nLemon - Myśl\nLeningrad\nLudzie Mili - Poeci\nMy Riot - Ból przemija\nProjekt Grechuta - Gdzieś w nas\nRootwater - Hava Nagila\nKindred - Kill the power\nThe Hive - Go right ahead  \n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:58', '2018-05-30 00:35:58'),
(104, 5, 'Retransmisja ASP - Agnieszka Holland #Woodstock2014', 'https://www.youtube.com/embed/U5aWvPypqXU', 'https://i.ytimg.com/vi/U5aWvPypqXU/default_live.jpg', NULL, 'Akademia Sztuk Przepięknych to miejsce bardzo ważnych spotkań i rozmów. Takim na pewno było to, które odbyło się w 2014 roku z światowej sławy reżyserką ...', 'Akademia Sztuk Przepięknych to miejsce bardzo ważnych spotkań i rozmów. Takim na pewno było to, które odbyło się w 2014 roku z światowej sławy reżyserką, pierwsza w historii kobietą prezydent Europejskiej Akademii Filmowej - Agnieszką Holland. Podczas prawie dwugodzinnej rozmowy poruszone zostało bardzo dużo kwestii dotyczących kina, świata filmu, ale również historii Polski.\n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:35:59', '2018-05-30 00:35:59'),
(105, 5, 'Jurek z prestiżową nagrodą Polonicus!', 'https://www.youtube.com/embed/lesJcEtPQ34', 'https://i.ytimg.com/vi/lesJcEtPQ34/default.jpg', NULL, '28 kwietnia w Akwizgranie z rąk europejskiej Polonii Jurek Owsiak otrzymał prestiżową nagrodę Polonicus za zaangażowanie w rozwój społeczeństwa ...', '28 kwietnia w Akwizgranie z rąk europejskiej Polonii Jurek Owsiak otrzymał prestiżową nagrodę Polonicus za zaangażowanie w rozwój społeczeństwa obywatelskiego. \n\nWśród laureatów znalazł sie również Donald Tusk - Przewodniczący Rady Europejskiej, oraz Benedykt i Róża Frąckiewiczowie, dyrygent i pierwsza solistka chóru Benedictus z Wuppertalu. \n\nZobaczcie naszą relecję z tego wydarzenia!', '2018-05-30 00:35:59', '2018-05-30 00:35:59'),
(106, 5, 'Retransmisja koncertu zespołu Shantel #Woodstock2012', 'https://www.youtube.com/embed/ZH7vBREj2Ps', 'https://i.ytimg.com/vi/ZH7vBREj2Ps/default.jpg', NULL, 'Shantel - muzyczny kosmopolita, międzykulturowy poszukiwacz i twórca międzygatunkowych brzmień, autor przeboju „Disko Partizani”. Artysta zagra wraz ze ...', 'Shantel - muzyczny kosmopolita, międzykulturowy poszukiwacz i twórca międzygatunkowych brzmień, autor przeboju „Disko Partizani”. Artysta zagra wraz ze swoją Bucovina Club Orkestar. Shantel to wyjątkowy twórca, który w ciągu kilku ostatnich lat stał się jednym z najlepszych towarów eksportowych Niemiec, nagradzany międzynarodowymi wyróżnieniami za swoje płyty, na których łączy tradycyjne bałkańskie brzmienia z klezmerskim feelingiem.\n\nPosłuchajcie tego koncertu w całości w czwartek (26.04) o godz. 18:00!\n\nSubskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:36:00', '2018-05-30 00:36:00'),
(107, 5, '#40 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/DoO7Z4_ooXs', 'https://i.ytimg.com/vi/DoO7Z4_ooXs/default.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami wybieracie!\n\n#40 Kręciołowa Dziesiątka:\nAcid Drinkers - Joker\nCounterfeit - Too old to live\nThe Dead Daisies - Long way to go\nKolory - Seventeen\nOddział Zamknięty - Ich marzenia\nOrange goblin - Made if rats\nProletariat - jak ptak\nThe Sixpounder - Fuel\nThe Bill - Kibel\nVoo Voo - Nim stanie się tak', '2018-05-30 00:36:00', '2018-05-30 00:36:00'),
(108, 5, '#44 Kręciołowa Dziesiątka', 'https://www.youtube.com/embed/bBg0QwDgwXw', 'https://i.ytimg.com/vi/bBg0QwDgwXw/default_live.jpg', NULL, 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami ...', 'Wy proponujecie woodstockowe numery, a my puszczamy je na żywo. Wpadajcie pogadać na czacie przy dobrej dawce woodstockowej muzy, którą sami wybieracie!\n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:36:00', '2018-05-30 00:36:00'),
(109, 5, 'Zobacz spotkanie z Kubą Wojewódzkim z #Woodstock2013', 'https://www.youtube.com/embed/VAzy2sqejCg', 'https://i.ytimg.com/vi/VAzy2sqejCg/default.jpg', NULL, 'Subskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX Tłumy jakie pojawiły się na spotkaniu z Kubą Wojewódzkim przerosły nasze najśmielsze oczekiwania.', 'Subskrybuj nasz kanał ➡ http://bit.ly/1w8ZNXX\n\nTłumy jakie pojawiły się na spotkaniu z Kubą Wojewódzkim przerosły nasze najśmielsze oczekiwania. Wiele osób stało przed namiotem oglądając wszystko na telebimie wystawionym obok Sceny Folkowej. Już na początku spotkania Kuba wzruszył się, kiedy cały namiot odśpiewał na jego cześć STO LAT - gość bowiem w dniu spotkania obchodził swoje 50 urodziny!\n\nPodczas rozmowy były momenty pełne śmiechu i żartów, ale zdarzały się również wyjątkowo poważne tematy. Posłuchajcie! \n\nKręcioła.Tv łapcie nas tu:\nFacebook - https://www.facebook.com/kreciola\nInstagram - http://instagram.com/kreciolatv\nTwitter - https://twitter.com/kreciolatv\nSnapchat - @kreciolatv', '2018-05-30 00:36:01', '2018-05-30 00:36:01'),
(110, 6, 'The Kooks Westside in Central Park NYC', 'https://www.youtube.com/embed/cLCl5NPRYz0', 'https://i.ytimg.com/vi/cLCl5NPRYz0/default.jpg', NULL, 'The Kooks performing Westside, from the album Listen, live in Central Park, New York June 2015. You shot the footage, we made the film. Big thanks to ...', 'The Kooks performing Westside, from the album Listen, live in Central Park, New York June 2015. You shot the footage, we made the film. Big thanks to everyone who took part.\n\n#thekookscentralpark2015\n\nListen\' out now. Get it from:\niTunes - http://po.st/iTListen\nAmazon - http://po.st/aListen\nOfficial Store -- http://smarturl.it/KooksListenStore\n\nSpotify - http://po.st/KooksSpotify\n\nJoin The Kooks:\n\nhttp://po.st/KooksTumblr\nhttp://instagram.com/thekooksmusic/\nhttp://twitter.com/thekooksmusic\nhttp://www.youtube.com/thekooksofficial\nhttp://po.st/KooksMerch\n\nhttp://www.thekooks.com\n#thekookscentralpark2015', '2018-05-30 00:36:01', '2018-05-30 00:36:01'),
(111, 6, 'The Kooks - Bad Habit (Mouthe Remix)', 'https://www.youtube.com/embed/vlA0xbLGXeM', 'https://i.ytimg.com/vi/vlA0xbLGXeM/default.jpg', NULL, 'Original version of Bad Habit available now on iTunes: http://smarturl.it/KooksListen?IQid=YT.mouthe Join The Kooks: http://po.st/KooksTumblr ...', 'Original version of Bad Habit available now on iTunes: http://smarturl.it/KooksListen?IQid=YT.mouthe\n\nJoin The Kooks:\n\nhttp://po.st/KooksTumblr\nhttp://instagram.com/thekooksmusic/\nhttp://twitter.com/thekooksmusic\nhttp://www.youtube.com/thekooksofficial\nhttp://po.st/KooksMerch\n\nhttp://www.thekooks.com', '2018-05-30 00:36:02', '2018-05-30 00:36:02'),
(112, 6, 'The Kooks - \'Listen\' Album Sampler', 'https://www.youtube.com/embed/VRxr1wp1wnw', 'https://i.ytimg.com/vi/VRxr1wp1wnw/default.jpg', NULL, 'Click the tracks above to sample The Kooks\' new album, \'Listen\' \'Listen\' is out now. Get it from: iTunes - http://po.st/iTListen Amazon - http://po.st/aListen Official ...', 'Click the tracks above to sample The Kooks\' new album, \'Listen\'\n\n\'Listen\' is out now. Get it from:\niTunes - http://po.st/iTListen\nAmazon - http://po.st/aListen\nOfficial Store -- http://smarturl.it/KooksListenStore\n\nSpotify - http://po.st/KooksSpotify\n\nJoin The Kooks:\n\nhttp://po.st/KooksTumblr\nhttp://instagram.com/thekooksmusic/\nhttp://twitter.com/thekooksmusic\nhttp://www.youtube.com/thekooksofficial\nhttp://po.st/KooksMerch\n\nhttp://www.thekooks.com', '2018-05-30 00:36:02', '2018-05-30 00:36:02'),
(113, 6, 'The Kooks - Around Town (on Alan Carr: Chatty Man)', 'https://www.youtube.com/embed/Weu4ZJHlM_c', 'https://i.ytimg.com/vi/Weu4ZJHlM_c/default.jpg', NULL, '\'Around Town\' is taken from the forthcoming album \'Listen\' Get \'Around town\' here: http://po.st/AroundTown New album \'Listen\' out now: http://po.st/iTListen Join ...', '\'Around Town\' is taken from the forthcoming album \'Listen\'\n\nGet \'Around town\' here: http://po.st/AroundTown\nNew album \'Listen\' out now: http://po.st/iTListen \n\nJoin The Kooks:\nhttp://po.st/KooksTumblr\nhttp://instagram.com/thekooksmusic/\nhttp://twitter.com/thekooksmusic\nhttp://www.youtube.com/thekooksofficial\nhttp://po.st/KooksMerch\n\nhttp://www.thekooks.com', '2018-05-30 00:36:02', '2018-05-30 00:36:02'),
(114, 6, 'The Kooks - Down (live at The Cow secret gig)', 'https://www.youtube.com/embed/sP_BbYruwtA', 'https://i.ytimg.com/vi/sP_BbYruwtA/default.jpg', NULL, '\'Down\' EP out now http://po.st/DowniT New album \'Listen\' out now: iTunes http://po.st/ListeniT iTunes Deluxe http://po.st/ListenDlx Amazon ...', '\'Down\' EP out now http://po.st/DowniT\n\nNew album \'Listen\' out now:\niTunes http://po.st/ListeniT\niTunes Deluxe http://po.st/ListenDlx\nAmazon http://po.st/ListenAmazon\nOfficial store http://smarturl.it/KooksListenStore\n\nhttps://www.facebook.com/thekooksofficial\nhttps://twitter.com/thekooksmusic\nhttp://thekooks.com/', '2018-05-30 00:36:03', '2018-05-30 00:36:03'),
(115, 6, 'The Kooks - HMH Amsterdam timelapse', 'https://www.youtube.com/embed/VHO1LwMlW6w', 'https://i.ytimg.com/vi/VHO1LwMlW6w/default.jpg', NULL, 'Get Junk Of The Heart for £3.95 from iTunes: http://bit.ly/sXcqDp. Or get the CD from £5.99 in these places: http://bit.ly/l3YVlY. The above timelapse was filmed in ...', 'Get Junk Of The Heart for £3.95 from iTunes: http://bit.ly/sXcqDp. Or get the CD from £5.99 in these places: http://bit.ly/l3YVlY.\n\nThe above timelapse was filmed in Amsterdam on the Junk Of The Heart European tour 2011 and demonstrates a glimpse of the amount of work that goes into each Kooks show. View upcoming dates at http://www.thekooks.com/.\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:03', '2018-05-30 00:36:03'),
(116, 6, 'The Kooks Rosie Lyric Video', 'https://www.youtube.com/embed/cpHtCJI29l0', 'https://i.ytimg.com/vi/cpHtCJI29l0/default.jpg', NULL, 'Rosie Lyric Video - taken from the new album \'Junk Of The Heart\' out now. Get it here: http://bit.ly/l3YVlY Like https://www.facebook.com/thekooksofficial Follow ...', 'Rosie Lyric Video - taken from the new album \'Junk Of The Heart\' out now. Get it here: http://bit.ly/l3YVlY \n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:03', '2018-05-30 00:36:03'),
(117, 6, 'The Kooks - \'Is It Me\' Lyric Video', 'https://www.youtube.com/embed/eKkYCr0vDTE', 'https://i.ytimg.com/vi/eKkYCr0vDTE/default.jpg', NULL, '\'Is It Me\' out now in the UK/IE - get it here http://bit.ly/qPHb1g iTunes EP includes a b-side + live tracks. Taken from the new album \'Junk Of The Heart\' out now: ...', '\'Is It Me\' out now in the UK/IE - get it here http://bit.ly/qPHb1g iTunes EP includes a b-side + live tracks. Taken from the new album \'Junk Of The Heart\' out now: http://bit.ly/l3YVlY  \n\nWin the chance to meet the Kooks in person at one of their upcoming tour dates by uploading a video of your cover of \'Is It Me\'! http://thekooks.com/isitme/\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:04', '2018-05-30 00:36:04'),
(118, 6, 'The Kooks - Junk Of The Heart (Happy)', 'https://www.youtube.com/embed/eCMykkcoyu8', 'https://i.ytimg.com/vi/eCMykkcoyu8/default.jpg', NULL, 'Junk Of The Heart (Happy) - OUT NOW Ex. UK / Eire Click Here To Buy http://bit.ly/rjYYM0 Order the new album here: http://bit.ly/l3YVlY Out 12th September UK ...', 'Junk Of The Heart (Happy) - OUT NOW  Ex. UK / Eire Click Here To Buy http://bit.ly/rjYYM0\n\nOrder the new album here: http://bit.ly/l3YVlY  Out 12th September UK / 13th US\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:04', '2018-05-30 00:36:04'),
(119, 6, 'The Kooks - The Saboteur', 'https://www.youtube.com/embed/nE4iBVmb6u4', 'https://i.ytimg.com/vi/nE4iBVmb6u4/default.jpg', NULL, 'New album \'Junk Of The Heart\' out now. Get it here: http://bit.ly/l3YVlY Like https://www.facebook.com/thekooksofficial Follow http://twitter.com/thekooksmusic ...', 'New album \'Junk Of The Heart\' out now. Get it here: http://bit.ly/l3YVlY\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:05', '2018-05-30 00:36:05'),
(120, 6, 'Princess Of My Mind', 'https://www.youtube.com/embed/PNAFWOghCUk', 'https://i.ytimg.com/vi/PNAFWOghCUk/default.jpg', NULL, 'Luke performs new song \"Princess Of My Mind\". Seasons Greetings and see you all in 2011. Pre-order the new album \'Junk Of The Heart\' here: ...', 'Luke performs new song \"Princess Of My Mind\". Seasons Greetings and see you all in 2011. Pre-order the new album \'Junk Of The Heart\' here: http://bit.ly/l3YVlY . Released September 12th UK/13th US.\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/\nhttp://thekooks.officialmerchshop.com/', '2018-05-30 00:36:05', '2018-05-30 00:36:05'),
(121, 6, 'The Kooks - Shine On live @ Pukkelpop 2010', 'https://www.youtube.com/embed/CT0NbUPz_yg', 'https://i.ytimg.com/vi/CT0NbUPz_yg/default.jpg', NULL, 'The Kooks perform \'Shine On\' from the album \'Konk\' at Pukkelpop 2010. Get \'Konk\' here: http://on.fb.me/kooksalbums Pre-order the new album \'Junk of The ...', 'The Kooks perform \'Shine On\' from the album \'Konk\' at Pukkelpop 2010. Get \'Konk\' here: http://on.fb.me/kooksalbums\n\nPre-order the new album \'Junk of The Heart\' here: http://bit.ly/l3YVlY \n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:05', '2018-05-30 00:36:05'),
(122, 6, 'The Kooks - MTV Ibiza Rocks 2010', 'https://www.youtube.com/embed/_tuX_jbLvjw', 'https://i.ytimg.com/vi/_tuX_jbLvjw/default.jpg', NULL, 'Interview with and behind the scenes footage of The Kooks for MTV at Ibiza Rocks 2010. Featuring tracks from the albums Konk and Inside In/Inside Out.', 'Interview with and behind the scenes footage of The Kooks for MTV at Ibiza Rocks 2010.\n\nFeaturing tracks from the albums Konk and Inside In/Inside Out. Download now on iTunes: http://bit.ly/dnwiux\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:06', '2018-05-30 00:36:06'),
(123, 6, 'The Kooks - Do You Wanna live @ Gurten Festival 2010', 'https://www.youtube.com/embed/ckrBWqBpx0o', 'https://i.ytimg.com/vi/ckrBWqBpx0o/default.jpg', NULL, 'Recorded live at Gurten Festival in Switzeland. \'Do You Wanna\' is taken from the album \'Konk\' which you can get from iTunes here: http://bit.ly/9lwLUd Like ...', 'Recorded live at Gurten Festival in Switzeland. \'Do You Wanna\' is taken from the album \'Konk\' which you can get from iTunes here: http://bit.ly/9lwLUd\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:06', '2018-05-30 00:36:06'),
(124, 6, 'The Kooks - Down To The Market @ Gurten Festival, 17th July 2010', 'https://www.youtube.com/embed/PLFrrvknoTY', 'https://i.ytimg.com/vi/PLFrrvknoTY/default.jpg', NULL, 'Visit http://www.facebook.com/thekooksofficial for official photos, updates and more. Down To The Market is taken from the album Konk. Download now on ...', 'Visit http://www.facebook.com/thekooksofficial for official photos, updates and more.\r\n\r\nDown To The Market is taken from the album Konk. Download now on iTunes: http://bit.ly/dnwiux', '2018-05-30 00:36:06', '2018-05-30 00:36:06'),
(125, 6, 'The Kooks Cover Song (Tears for Fears - Head Over Heels)', 'https://www.youtube.com/embed/FCOgGO7PgbU', 'https://i.ytimg.com/vi/FCOgGO7PgbU/default.jpg', NULL, 'Head Over Heels by The Kooks, originally by Tears for Fears Like https://www.facebook.com/thekooksofficial Follow http://twitter.com/thekooksmusic Sign up for ...', 'Head Over Heels by The Kooks, originally by Tears for Fears\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:07', '2018-05-30 00:36:07'),
(126, 6, 'The Kooks - See The Sun (tour bus)', 'https://www.youtube.com/embed/G20wMUBTHg8', 'https://i.ytimg.com/vi/G20wMUBTHg8/default.jpg', NULL, 'Like https://www.facebook.com/thekooksofficial Follow http://twitter.com/thekooksmusic Sign up for updates at http://thekooks.com/', 'Like https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:07', '2018-05-30 00:36:07'),
(127, 6, 'The Kooks - Watching The Ships Roll In (tour bus)', 'https://www.youtube.com/embed/W9BoAcbQdc4', 'https://i.ytimg.com/vi/W9BoAcbQdc4/default.jpg', NULL, 'http://www.THEKOOKS.com/', 'http://www.THEKOOKS.com/', '2018-05-30 00:36:07', '2018-05-30 00:36:07'),
(128, 6, 'The Kooks - Ibiza Rocks 2009', 'https://www.youtube.com/embed/gbLY3XtTmyc', 'https://i.ytimg.com/vi/gbLY3XtTmyc/default.jpg', NULL, 'Behind the scenes footage of The Kooks appearance at Ibiza Rocks 2009. http://www.THEKOOKS.com/ Like https://www.facebook.com/thekooksofficial Follow ...', 'Behind the scenes footage of The Kooks appearance at Ibiza Rocks 2009.\nhttp://www.THEKOOKS.com/\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:08', '2018-05-30 00:36:08'),
(129, 6, 'The Kooks post-Europe Thank You message', 'https://www.youtube.com/embed/epuKJVpTjZo', 'https://i.ytimg.com/vi/epuKJVpTjZo/default.jpg', NULL, 'Thank you message from The Kooks to all fans who made it to one of the shows over May/June/July \'09. Filmed just before going on stage @ Eden Sessions ...', 'Thank you message from The Kooks to all fans who made it to one of the shows over May/June/July \'09. Filmed just before going on stage @ Eden Sessions 18/07/09.\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:08', '2018-05-30 00:36:08'),
(130, 6, 'The Kooks in South America', 'https://www.youtube.com/embed/CzSHrTK_anE', 'https://i.ytimg.com/vi/CzSHrTK_anE/default.jpg', NULL, 'Video footage of The Kooks dates in Chile, Argentina and Brazil. June 2009. Like https://www.facebook.com/thekooksofficial Follow ...', 'Video footage of The Kooks dates in Chile, Argentina and Brazil. June 2009.\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:08', '2018-05-30 00:36:08'),
(131, 6, 'The Kooks in Berlin - 25th April 2009 (Discl.: CONTAINS FLASHING LIGHTS)', 'https://www.youtube.com/embed/gyfRTSrqMQE', 'https://i.ytimg.com/vi/gyfRTSrqMQE/default.jpg', NULL, 'DISCLAIMER: CONTAINS FLASHING LIGHTS* Video of The Kooks trip to Berlin in April. The Kooks headlined a sold out night of the Soundwave Discovery Tour ...', '*DISCLAIMER: CONTAINS FLASHING LIGHTS*\nVideo of The Kooks trip to Berlin in April. \nThe Kooks headlined a sold out night of the Soundwave Discovery Tour 2009 at the Berlin Arena.\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:09', '2018-05-30 00:36:09'),
(132, 6, 'The Kooks - Bandwagon @ Zanzibar Club, Liverpool 22-04-09', 'https://www.youtube.com/embed/HI5NXXvRLVA', 'https://i.ytimg.com/vi/HI5NXXvRLVA/default.jpg', NULL, 'Higlights from The Kooks exclusive intimate show at the Bandwagon clubnight @ Zanzibar, Liverpool, back in April. The show was announced a week before ...', 'Higlights from The Kooks exclusive intimate show at the Bandwagon clubnight @ Zanzibar, Liverpool, back in April. The show was announced a week before taking place via THEKOOKS.com and the band\'s mailing list, with tickets available only from Probe Records. Tickets sold out within minutes - watch the video to see how it turned out....\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:09', '2018-05-30 00:36:09'),
(133, 6, 'The Kooks 3rd album writing session in Marseilles', 'https://www.youtube.com/embed/FvjB0Drb3hI', 'https://i.ytimg.com/vi/FvjB0Drb3hI/default.jpg', 4, 'Keep checking THEKOOKS.com for more video footage & photos from the road. Like https://www.facebook.com/thekooksofficial Follow ...', 'Keep checking THEKOOKS.com for more video footage & photos from the road.\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:10', '2018-05-30 00:44:23'),
(134, 6, 'The Kooks go Go Karting', 'https://www.youtube.com/embed/WONjbgbVh24', 'https://i.ytimg.com/vi/WONjbgbVh24/default.jpg', NULL, 'The Kooks go Go Karting in France - stay tuned for more footage of The Kooks on the road. Like https://www.facebook.com/thekooksofficial Follow ...', 'The Kooks go Go Karting in France - stay tuned for more footage of The Kooks on the road.\n\nLike https://www.facebook.com/thekooksofficial \nFollow http://twitter.com/thekooksmusic\nSign up for updates at http://thekooks.com/', '2018-05-30 00:36:10', '2018-05-30 00:36:10');

--
-- Indeksy dla zrzutów tabel
--

--
-- Indeksy dla tabeli `channel`
--
ALTER TABLE `channel`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQ_A2F98E475E237E06` (`name`);

--
-- Indeksy dla tabeli `movie`
--
ALTER TABLE `movie`
  ADD PRIMARY KEY (`id`),
  ADD KEY `IDX_1D5EF26F72F5A1AA` (`channel_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT dla tabeli `channel`
--
ALTER TABLE `channel`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT dla tabeli `movie`
--
ALTER TABLE `movie`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=135;

--
-- Ograniczenia dla zrzutów tabel
--

--
-- Ograniczenia dla tabeli `movie`
--
ALTER TABLE `movie`
  ADD CONSTRAINT `FK_1D5EF26F72F5A1AA` FOREIGN KEY (`channel_id`) REFERENCES `channel` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
